{{- if $.Values.apigateway.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.{{ $.Values.global.clusterName }}.{{ $.Values.global.domainName }}`)
      services:
        - name: whoami-noui
          port: 80
  tls: {}
