{{- if $.Values.apim.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingress-employees
  namespace: apps
  annotations:
    hub.traefik.io/api: "employee-api"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.{{ $.Values.apim.apiAuth.clusterName }}.{{ $.Values.apim.apiAuth.domainName }}`) && PathPrefix(`/employees`)
      services:
        - name: employee-app-latency
          port: 3000
  tls: {}
